In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [21]:
inputs = torch.randn(3, 3)
inputs

tensor([[ 0.0038, -0.4960,  0.7453],
        [-0.2307, -0.6004,  1.2908],
        [-1.0839, -1.1705, -1.2535]])

In [22]:
sm = nn.Softmax(dim=1)
sm_out = sm(inputs)
sm_out

tensor([[0.2699, 0.1637, 0.5664],
        [0.1595, 0.1102, 0.7303],
        [0.3622, 0.3321, 0.3057]])

In [23]:
sm_out.sum(dim=1)

tensor([1., 1., 1.])

In [24]:
sm_log_out = torch.log(sm_out)
sm_log_out

tensor([[-1.3099, -1.8097, -0.5684],
        [-1.8358, -2.2054, -0.3143],
        [-1.0156, -1.1022, -1.1852]])

In [25]:
# 计算NLLLoss
# 假设我们现在Target是[1, 0, 2]（第一张图片是猫，第二张是狗，第三张是熊）。
# 在log_softmax的计算结果中（每一行代表一个样本），第一行取第1个元素，第二行取第0个，第三行取第2个，去掉负号
# 再求个均值
target = torch.tensor([1, 0, 2])

In [26]:
# 手动计算
-((-0.4073) + (-1.8207) + (-0.9087)) / 3

1.0455666666666665

In [27]:
loss = nn.NLLLoss()
loss(sm_log_out, target)

tensor(1.6102)

In [28]:
# CrossEntropyLoss就是log_softmax与NLLLoss组合起来的操作

loss2 = nn.CrossEntropyLoss()

In [30]:
inputs

tensor([[ 0.0038, -0.4960,  0.7453],
        [-0.2307, -0.6004,  1.2908],
        [-1.0839, -1.1705, -1.2535]])

In [31]:
target

tensor([1, 0, 2])

In [33]:
loss2(inputs, target)

tensor(1.6102)

In [36]:
from torch.utils.data import Dataset, DataLoader

In [37]:
class RnnlmDataset(Dataset):
    
    def __init__(self, corpus, vocab):
        self.data = []
        self.bos = vocab

IndentationError: expected an indented block (557997044.py, line 1)